/**
 * "Ask the AI" chat — an on-device assistant that answers questions from
 * the app's live analysis state (storm scores, environment, alerts, week
 * outlook). No external AI service, no account, no data leaves the phone;
 * answers are generated by intent-matching + the same narrative engine
 * that powers the analysis panels, and always carry the unofficial-
 * estimate disclaimer.
 */
import { el, fmtDistance, fmtSpeed, compassDir } from '../utils.js';
import { settings } from '../storage.js';
import { getState } from '../api/sources.js';
import { getLocation } from '../location.js';
import { stormSummary, tornadoStatement } from '../analysis/narrative.js';
import { pointInGeometry } from '../analysis/stormAnalyzer.js';

let transcript = []; // {who: 'you'|'ai', text}
let getAnalyses = () => [];
let onSelectStorm = () => {};

export function initChat({ analysesProvider, onSelect }) {
  getAnalyses = analysesProvider;
  onSelectStorm = onSelect;
  const sheet = document.getElementById('chat-sheet');
  sheet.querySelector('.sheet-grab').addEventListener('click', () => { sheet.hidden = true; });
  document.getElementById('chat-send').addEventListener('click', send);
  document.getElementById('chat-input').addEventListener('keydown', (e) => {
    if (e.key === 'Enter') send();
  });
  // Quick-question chips.
  const chips = [
    'Which storm has the most tornado potential?',
    'When will the closest storm reach me?',
    'Is it safe right now?',
    'What does this week look like?',
  ];
  const chipRow = document.getElementById('chat-chips');
  for (const q of chips) {
    chipRow.appendChild(el('button', {
      class: 'chat-chip', text: q,
      onclick: () => { document.getElementById('chat-input').value = q; send(); },
    }));
  }
}

export function openChat() {
  document.getElementById('chat-sheet').hidden = false;
  if (!transcript.length) {
    push('ai', 'Hi — I answer questions using the live radar analysis on this device. Ask me things like “which storm near me could produce a tornado?”, “when will the closest storm hit?”, “what about hail?”, or “what does this week look like?” Everything I say is an unofficial estimate — always follow NWS warnings.');
  }
  render();
}

function send() {
  const input = document.getElementById('chat-input');
  const q = input.value.trim();
  if (!q) return;
  input.value = '';
  push('you', q);
  push('ai', answer(q));
  render();
}

function push(who, text) {
  transcript.push({ who, text });
  if (transcript.length > 60) transcript.shift();
}

function render() {
  const log = document.getElementById('chat-log');
  log.textContent = '';
  for (const m of transcript) {
    log.appendChild(el('div', { class: `chat-msg ${m.who}`, text: m.text }));
  }
  log.scrollTop = log.scrollHeight;
}

/* ------------------------- answer engine ------------------------- */

function answer(qRaw) {
  const q = qRaw.toLowerCase();
  const user = getLocation();
  const all = getAnalyses();
  const near = user
    ? all.filter((a) => a.userRel && a.userRel.distKm <= settings.monitorRadiusKm)
    : all;
  const pool = near.length ? near : all;
  const scope = user ? (near.length ? 'near you' : 'nationally (none in your radius)') : 'nationally (no GPS)';

  const has = (...words) => words.some((w) => q.includes(w));

  // --- tornado potential ---------------------------------------------------
  if (has('tornado', 'rotation', 'spin', 'funnel')) {
    if (!pool.length) return noStorms(user);
    const top = [...pool].sort((a, b) => b.tornado.score - a.tornado.score)[0];
    let out = `The storm with the highest tornado potential ${scope} is ${ident(top)} — tornado score ${top.tornado.score}/100, chance ${top.tornado.label} (${top.tornado.pct}). `;
    out += tornadoStatement(top);
    return out + tapHint(top);
  }

  // --- hail / wind / flood / lightning ---------------------------------------
  const hazardMap = [
    [['hail'], 'hail', 'hail'],
    [['wind', 'gust', 'derecho'], 'wind', 'damaging wind'],
    [['flood', 'rain'], 'flood', 'flash flooding'],
    [['lightning', 'strike'], 'lightning', 'lightning'],
  ];
  for (const [words, key, label] of hazardMap) {
    if (has(...words)) {
      if (!pool.length) return noStorms(user);
      const top = [...pool].sort((a, b) => b.scores[key] - a.scores[key])[0];
      return `The biggest ${label} threat ${scope} is ${ident(top)} with a ${label} score of ${Math.round(top.scores[key])}/100. ${stormSummary(top)} ${disclaimer()}${tapHint(top)}`;
    }
  }

  // --- arrival / closest ------------------------------------------------------
  if (has('closest', 'nearest', 'hit me', 'arrive', 'reach me', 'when will', 'how far', 'how long', 'eta')) {
    if (!user) return 'I need your location for that — tap the ⌖ button on the map and allow location, then ask again.';
    const withDist = all.filter((a) => a.userRel).sort((x, y) => x.userRel.distKm - y.userRel.distKm);
    if (!withDist.length) return noStorms(user);
    const c = withDist[0];
    let out = `The closest storm is ${ident(c)}, ${fmtDistance(c.userRel.distKm, settings.units)} away, moving ${compassDir(c.cell.moveDirDeg ?? 0)} at ${fmtSpeed(c.cell.moveSpeedKts ?? 0, settings.units)}. `;
    out += c.userRel.etaMin != null
      ? `On its current track it reaches your area in roughly ${c.userRel.etaMin} minutes. `
      : `Its current track does NOT bring it over your location, though storms can turn. `;
    return out + disclaimer() + tapHint(c);
  }

  // --- safety ------------------------------------------------------------------
  if (has('safe', 'worry', 'danger', 'shelter', 'scared')) {
    return safetyAnswer(user, all);
  }

  // --- week ahead / forecast ------------------------------------------------------
  if (has('week', 'tomorrow', 'forecast', 'coming days', 'next few days', 'this weekend', 'later')) {
    return weekAnswer();
  }

  // --- environment ------------------------------------------------------------------
  if (has('cape', 'shear', 'environment', 'helicity', 'instability', 'setup', 'atmosphere')) {
    const env = getState().environment;
    if (!env) return 'Model environment data hasn\'t loaded yet — give it a moment or move the map to your area.';
    return `Near your focus point: CAPE ≈ ${Math.round(env.cape ?? 0)} J/kg, deep-layer shear ≈ ${Math.round(env.bulkShearKts ?? 0)} kt, estimated storm-relative helicity ≈ ${env.srh ?? '?'} m²/s², cloud base ≈ ${env.lclM != null ? Math.round(env.lclM) + ' m' : '?'}. ${(env.bulkShearKts ?? 0) >= 40 && (env.cape ?? 0) >= 1000 ? 'That combination supports supercells if storms can develop.' : 'The full AI Analyst tab has the complete environment discussion and hodograph.'} ${disclaimer()}`;
  }

  // --- warnings ------------------------------------------------------------------
  if (has('warning', 'watch', 'alert')) {
    const alerts = getState().alerts;
    const tor = alerts.filter((a) => a.kind === 'tor-warning').length;
    const svr = alerts.filter((a) => a.kind === 'svr-warning').length;
    const ffw = alerts.filter((a) => a.kind === 'ffw-warning').length;
    if (!tor && !svr && !ffw) return 'No tornado, severe thunderstorm, or flash flood WARNINGS are active in the feed right now. The Alerts tab lists watches too, sorted by distance from you.';
    return `Active right now: ${tor} tornado warning${tor === 1 ? '' : 's'}, ${svr} severe thunderstorm warning${svr === 1 ? '' : 's'}, ${ffw} flash flood warning${ffw === 1 ? '' : 's'}. Open the Alerts tab to see which are closest to you — these are official NWS products.`;
  }

  // --- strongest / most dangerous overall -----------------------------------------
  if (has('strongest', 'worst', 'most dangerous', 'biggest', 'severe')) {
    if (!pool.length) return noStorms(user);
    const top = pool[0];
    return `The most dangerous storm ${scope} is ${ident(top)} at ${top.severeScore}/100 (${top.threatRating.label}). ${stormSummary(top)} ${disclaimer()}${tapHint(top)}`;
  }

  // --- fallback: quick situation + what I can answer -------------------------------
  const count = pool.length;
  return `I'm not sure how to answer that one. Right now I'm tracking ${count} storm${count === 1 ? '' : 's'} ${scope}. You can ask me about: tornado / hail / wind / flood potential, the closest storm and when it arrives, whether it's safe, active warnings, the environment (CAPE/shear), or the week ahead.`;
}

function ident(a) {
  const dist = a.userRel ? `, ${fmtDistance(a.userRel.distKm, settings.units)} ${compassDir(bearingFromUser(a))} of you` : '';
  return `${a.type.label} ${a.cell.id}${dist}`;
}

function bearingFromUser(a) {
  const user = getLocation();
  if (!user) return 0;
  const dLon = (a.cell.lon - user.lon) * Math.PI / 180;
  const y = Math.sin(dLon) * Math.cos(a.cell.lat * Math.PI / 180);
  const x = Math.cos(user.lat * Math.PI / 180) * Math.sin(a.cell.lat * Math.PI / 180) -
    Math.sin(user.lat * Math.PI / 180) * Math.cos(a.cell.lat * Math.PI / 180) * Math.cos(dLon);
  return ((Math.atan2(y, x) * 180 / Math.PI) + 360) % 360;
}

function safetyAnswer(user, all) {
  if (!user) return 'Turn on location (⌖ on the map) and I can check the warnings and storms around you specifically.';
  const alerts = getState().alerts;
  let inTor = false, inSvr = false;
  for (const a of alerts) {
    if (!a.geometry) continue;
    if (pointInGeometry(user.lat, user.lon, a.geometry)) {
      if (a.kind === 'tor-warning') inTor = true;
      if (a.kind === 'svr-warning') inSvr = true;
    }
  }
  if (inTor) return '🚨 A TORNADO WARNING includes your location RIGHT NOW. Go to a basement or small interior room on the lowest floor, away from windows, immediately. Do not wait to confirm visually. This one is official — act on it.';
  if (inSvr) return '⛈ A Severe Thunderstorm Warning includes your location — move indoors, away from windows, and expect damaging wind or hail. That part is official NWS guidance.';
  const near = all.filter((a) => a.userRel && a.userRel.distKm <= 80);
  if (!near.length) return 'You are not inside any warning, and no tracked storms are within ~50 miles right now. Conditions can change fast — I\'ll keep watching and the alert engine will notify you.';
  const worst = near[0];
  return `You're not inside any official warning right now, but ${ident(worst)} is scoring ${worst.severeScore}/100${worst.userRel.etaMin != null ? ` and could reach your area in ~${worst.userRel.etaMin} min` : ''}. Keep alerts on and have a plan for shelter. ${disclaimer()}`;
}

function weekAnswer() {
  const week = getState().week;
  if (!week?.length) return 'The week-ahead outlook hasn\'t loaded yet — check the AI Analyst tab in a minute, or set a location first.';
  const active = week.filter((d) => d.level >= 1);
  const best = [...week].sort((a, b) => b.level - a.level || b.capeMax - a.capeMax)[0];
  const dayName = (date) => new Date(`${date}T12:00`).toLocaleDateString([], { weekday: 'long' });
  if (!active.length) {
    return `The next 7 days look quiet at your location — no day shows meaningful storm fuel. The Week Ahead card in the AI Analyst tab has the day-by-day details.`;
  }
  const list = active.map((d) => `${dayName(d.date)} (${d.label})`).join(', ');
  return `Storms are possible on: ${list}. The most interesting day looks like ${dayName(best.date)} — ${best.label} potential with CAPE to ~${best.capeMax} J/kg and deep shear to ~${best.shearMaxKts} kt. ${best.note} Model outlooks this far out shift daily, so recheck each morning. ${disclaimer()}`;
}

function noStorms(user) {
  return user
    ? 'No storm cells are currently being tracked within your monitoring radius. If storms fire, they\'ll appear on the map and I\'ll be able to rank them for you.'
    : 'No storm cells are being tracked right now, and I don\'t have your location — tap ⌖ on the map to enable it.';
}

function disclaimer() {
  return 'Unofficial AI estimate — not an NWS forecast.';
}

function tapHint(a) {
  // Store the referenced storm so a tap on the hint bubble could open it later;
  // for now we keep it textual and simple.
  return ` (Tap its ${a.severeScore} circle on the map for full details.)`;
}
